### ISSUE TITLE
invalid: metadata.resourceVersion Issue

### ISSUE THREAD

**Issue by CtrlAltDft** [alekc/terraform-provider-kubectl#185]
Recently I have been facing `invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update` when updating resources.

This seems to be because we did not pass in any value for `resourceVersion`

One suggestion is that we can get version from the existing resource and pass it to the new one?

**Comment by alekc** [comment]
Could you provide tf code you are trying to deploy? I am confused why you are mentioning `resourceVersion` since it's a generated field.

**Comment by Cytrian** [comment]
We have the same issue, this may be related. https://stackoverflow.com/questions/71581444/how-to-fix-metadata-resourceversion-invalid-value-must-be-specified-for-an
I cannot say for sure, maybe this happened: "So, for some reason, the value resourceVersion managed to be written in your last-applied-configuration, probably because of someone exporting the live manifests to a file, modifying it, and applying it back again."

**Comment by alekc** [comment]
Closing this off since there was no answer from original reporter. Feel free to ask for reopen
