### ISSUE TITLE
Motivation of the fork

### ISSUE THREAD

**Issue by tstrohmeier** [alekc/terraform-provider-kubectl#19]
Hi,

@alekc What was your motivation to fork the https://github.com/gavinbunney/terraform-provider-kubectl repo?

LG,
Thomas

**Comment by alekc** [comment]
Hi @tstrohmeier , pretty much it started with https://github.com/gavinbunney/terraform-provider-kubectl/pull/153 where it took 6m to merge this vital pr (and never release). Since it was vital for me to wait for the actual deletion of the object (while finalizer was working) hence the reason of the fork. Since then I've added some extra functionality as well. 

Closing this off for now, feel free to continue the discussion if you want :)
