### ISSUE TITLE
chore: Change test matrix

### ISSUE THREAD

**Issue by stevehipwell** [alekc/terraform-provider-kubectl#191]
The test matrix can be derived from https://endoflife.date/terraform & https://endoflife.date/kubernetes so it's always up to date. I'm happy to do the work but it'd be useful to have a set of constraints as for how many versions back to go or if only in-support versions should be tested. @alekc do you have an opinion on this?

**Comment by alekc** [comment]
So. For the kubernetes its easy, I would say 5-6 versions should be fine (sorry legacy / airgapped users). For terraform its a bit more complicated. I've kept 0.15 and 1.2 since there were breaking changes, but couple of years has passed and I would be very tempted to keep 5-6 of them as well. 

Thoughts?

**Comment by stevehipwell** [comment]
For TF I'd suggest supporting `1.5.7` (as the last OSS version) and then the 3 latest which is usually going to be in support +1.

For K8s as the client-go version generally tracks the latest K8s version so based on that it might be worth only testing in-support versions +1 (for overlap)? I'd also suggest that as part of the client-go update task a release is cut and a supported versions table is added to the README (just covering the fully supported version, not the tested versions). This way if you need old K8s version support and the new code breaks it you can use an old provider version as if something breaks I suspect it's likely to be in client-go rather than the provider code.
