### ISSUE TITLE
Is kubectl_path_documents order of files predictive?

### ISSUE THREAD

**Issue by jorgemoralespou** [alekc/terraform-provider-kubectl#56]
I've noticed in the docs this comment:

` Note that if the document order is changed (i.e. a new file is added), then it would trigger destruction and recreation of related documents.`

Is the order of the manifests list predictive? Can I be sure that if I add a prefix order (e.g. `01_`, `02_`) to file names, the order will be always the same so that I can add one file with index greater than last and prevent all previous resources to be deleted?

**Comment by alekc** [comment]
If you use this pattern:
```
data "kubectl_path_documents" "manifests-directory-yaml" {
  pattern = "./manifests/*.yaml"
}
resource "kubectl_manifest" "directory-yaml" {
  for_each  = data.kubectl_path_documents.manifests-directory-yaml.manifests
  yaml_body = each.value
}
```
there are no issues, because the key which identifies an object will be derived by a unique combination of Api/ns/nameofObject

That note was referring to use of count which doesn't use this unique identifier and thus can trigger a shift in objects in case new files are added.
